language: rust
os:
  - linux
  - osx
rust:
  - stable
  - nightly
matrix:
  exclude:
    - rust: stable
      env: FEATURE=nightly
  allow_failures:
    - os: osx
    - rust: nightly
      env: FEATURE=nightly
before_script:
  - pip install 'travis-cargo<0.2' --user  && export PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
script:
  - travis-cargo test -- --features $FEATURE --no-default-features
  - travis-cargo build -- --manifest-path examples/drive_example/Cargo.toml
  - travis-cargo build -- --manifest-path examples/service_account/Cargo.toml
after_success:
  - "[[ $TRAVIS_OS_NAME = linux ]] && travis-cargo --only stable coveralls"
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  matrix:
    - FEATURE=with-serde-codegen
    - FEATURE=nightly
