on: [push, pull_request]

name: Actions CI

jobs:
  build_and_test:
    name: yup-oauth2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --tests --examples
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples

  doc:
    name: yup-oauth2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features
        env:
          RUSTDOCFLAGS: --cfg yup_oauth2_docsrs
